baseURL = "https://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "PaperMod"

[params]
defaultTheme = "dark"
comments = true
showReadingTime = true

#[menu]
#[[menu.main]]
#name = "Tags"
#url = "/tags/"
#weight = 10

[caches]
[caches.images]
dir = ':cacheDir/images'